# .readthedocs.yaml
# Read the Docs configuration file
# https://docs.readthedocs.io/en/stable/config-file/v2.html

# Instructions/example on how to configure for projects managed by poetry:
# https://docs.readthedocs.io/en/stable/build-customization.html#install-dependencies-with-poetry
# Note:   these instructions were changed in Feb 2024 to fix an issue 
#         introduced by changes in poetry 1.8, see
#         https://github.com/readthedocs/readthedocs.org/pull/11152
#         https://github.com/readthedocs/readthedocs.org/issues/11150

version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  jobs:
    post_create_environment:
      # Install poetry
      # https://python-poetry.org/docs/#installing-manually
      - pip install poetry
      # Install dynamic versioning plugin
      # https://pypi.org/project/poetry-dynamic-versioning/
      - poetry self add "poetry-dynamic-versioning[plugin]" 
    post_install:
      # Install dependencies with 'docs' dependency group
      # https://python-poetry.org/docs/managing-dependencies/#dependency-groups
      # VIRTUAL_ENV needs to be set manually for now.
      # See https://github.com/readthedocs/readthedocs.org/pull/11152/
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH poetry install --with docs

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: true
