[tool.poetry]
name = "qats"
version = "0.0.0"   # overridden by dynamic versioning, must still be specified
description = "Library for efficient processing and visualization of time series"
authors = [
    "Per Voie <per.voie@gmail.com>", 
    "Erling Lone <erling.lone@gmail.com>"
    ]
# Repo and docs are optional fields in the project section. Consider to keep it here or to gather 
# all URLs in the url section
repository = "https://github.com/dnvgl/qats"
documentation = "https://qats.readthedocs.io"
license = "MIT"
readme = "README.md"
include = [
    "LICENSE",
    "CHANGELOG.md"
]

[tool.poetry.dependencies]
python = ">=3.8.1,<3.13"
h5py = ">=3.5.0"
pymatreader = ">=0.0.24"
matplotlib = ">=3.3.3"
nptdms = ">=1.1.0"
numpy = [
    {version = ">=1.21.6", python = "<3.12"},
    {version = ">=1.26.0", python = ">=3.12"}
]
openpyxl = ">=3.0.5"
pandas = ">=1.1.4"
qtpy = ">=1.9.0"
scipy = [
    {version = ">=1.9.0", python = "<3.12"},
    {version = ">=1.11.1", python = ">=3.12"}
]
pywin32 = {version = "^306", markers = "platform_system == 'Windows'"} # MUST check the appropriate constraint
pyside6 = "^6.6.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.3"
flake8 = "^6.1.0"
black = "^23.11.0"
isort = "^5.12.0"

[tool.poetry.group.docs.dependencies]
sphinx = ">=6.1"
furo = ">=2023.9.10"
myst-parser = ">=2.0.0"

[tool.poetry.scripts]
qats = "qats.cli:main"
qats-app = "qats.cli:launch_app"
# I expected the below solution to work but it does not. I will find a solution to
# launch the application without a console window.
#qats-app = {source = "qats.cli:launch_app", type = "gui"}
#qats = {source = "qats.cli:main", type = "console"}


[tool.poetry.urls]
Source = "https://github.com/dnvgl/qats"
Documentation = "https://qats.readthedocs.io"
Download = "https://pypi.org/project/qats/"
Issues = "https://github.com/dnvgl/qats/issues"

# enable dynamic versioning using Git tags
# https://sam.hooke.me/note/2023/08/poetry-automatically-generated-package-version-from-git-commit/
# https://pypi.org/project/poetry-dynamic-versioning/
[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
pattern  = "^(?P<base>\\d+\\.\\d+\\.\\d+)(-?((?P<stage>[a-zA-Z]+)\\.?(?P<revision>\\d+)?))?"
format-jinja = """
    {%- if distance == 0 -%}
        {{- base -}}
    {%- else -%}
        {{- base }}.dev{{ distance }}+g{{commit}}
    {%- endif -%}
"""
format-jinja-imports = [
    { module = "datetime", item = "datetime" }
]

[tool.poetry-dynamic-versioning.files."qats/_version.py"]
persistent-substitution = true
initial-content = """
# file generated by poetry dynamic versioning
# don't change, don't track in version control
__version__ = "0.0.0"
__version_tuple__ = (0, 0, 0)
"""

[build-system]
# https://pypi.org/project/poetry-dynamic-versioning/
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning>=1.1.1,<2.0.0"]
build-backend = "poetry_dynamic_versioning.backend"  # "poetry.core.masonry.api"
